no trim
can it fix these errors ?

ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 16.4.7107 is Xcode 14.3 or later. The current Xcode version (found in /Applications/Xcode_14.2.app/Contents/Developer) is 14.2. [/Users/runner/work/AvaloniaGraphControl/AvaloniaGraphControl/sample.iOS/AvaloniaGraphControlSample.iOS.csproj]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/AvaloniaGraphControl/AvaloniaGraphControl/sample.iOS/AvaloniaGraphControlSample.iOS.csproj]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/AvaloniaGraphControl/AvaloniaGraphControl/sample.iOS/AvaloniaGraphControlSample.iOS.csproj]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/runner/work/AvaloniaGraphControl/AvaloniaGraphControl/sample.iOS/AvaloniaGraphControlSample.iOS.csproj]
Error: /Users/runner/.dotnet/sdk/7.0.402/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/runner/work/AvaloniaGraphControl/AvaloniaGraphControl/sample.iOS/AvaloniaGraphControlSample.iOS.csproj]